apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dejavu
  name: dejavu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dejavu
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: dejavu
    spec:
      containers:
        - image: appbaseio/dejavu:3.2.3
          name: dejavu
          ports:
            - containerPort: 1358
          resources: {}
      restartPolicy: Always
status: {}
